/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package vn.rever.thrift.leadservice;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum OperationalError implements org.apache.thrift.TEnum {
  SAME_ID_EXISTED(0),
  REQUESTED_ID_NOT_EXISTS(1),
  NO_RECORD_FOUND(2);

  private final int value;

  private OperationalError(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static OperationalError findByValue(int value) { 
    switch (value) {
      case 0:
        return SAME_ID_EXISTED;
      case 1:
        return REQUESTED_ID_NOT_EXISTS;
      case 2:
        return NO_RECORD_FOUND;
      default:
        return null;
    }
  }
}
